# Assignment-3 (NumPy and SciPy)

Scope - In this assignment we will cover the basics of NumPy and SciPy usign various inbuild packages and simple examples. 

# NumPy
NumPy is the fundamental package for scientific computing with Python. It contains among other things:

-A powerful N-dimensional array object
-Sophisticated (broadcasting) functions
-Tools for integrating C/C++ and Fortran code
-Useful linear algebra, Fourier transform, and random number capabilities
Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.

# Arrays
A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

In [229]:
#Let us first import the numpy package before we use it. We will rename numpy as np.

import numpy as np

# Basic Attributes

In [230]:
#Following are some of the important attributes in numpy.

#Let us find the number of axes (dimensions) of the array. It is given by "nparray.ndim".
print(g.ndim)

#Let us find the dimensions of the array.For a matrix with n rows and m columns, shape will be (n,m). 
#The length of the shape tuple is therefore the number of axes, "ndim".
print(g.shape)

#let us find the total number of elements of the array. We use "nparray.size".
print(g.size)

#Let us find the type of the element. We use "nparray.dtype".
print(g.dtype)

#Let us find the size in bytes of each element of the array. For that we use "nparray.itemsize".
print(g.itemsize)

#Let us find the buffer containing the actual elements of the array. Basically gives the memory location using "nparray.data"
print(g.data)

1
(6,)
6
int32
4


In [231]:
#Let us create a list of grades for 6 students.

grades= [8,3,4,7,9,6]
#Let us now convert the list into a one-deimentional array. We use np.array() to create an array.
g= np.array(grades)
print(g)

[8 3 4 7 9 6]


In [232]:
#Let us find the average of the grades of all the students.It is very easy to achieve with a numpy array 
#using simple scalar multipilcation

s=sum(g)
print(s)
l=len(g)
print(l)
avg = s/l 
print(avg)

37
6
6.166666666666667


In [233]:
#Following is an example of two-dimentional array.
b = np.array([(1,2,3),(4,5,6)])
print(b)

[[1 2 3]
 [4 5 6]]


In [234]:
#We can also give the type to all the elements in the array. For example if we want to convert it into float.
b = np.array([(1,2,3),(4,5,6)], dtype=float)
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [235]:
#The function zeros creates an array full of zeros. 

np.zeros( (3,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [236]:
#The function ones creates an array full of ones.

np.ones( (2,3,4), dtype=np.int16 )                

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [237]:
#The function empty creates an array whose initial content is random and depends on the state of the memory.

np.empty( (2,3) )

array([[1., 2., 3.],
       [4., 5., 6.]])

In [238]:
#Let us find the sequence of number between two given number at regular interval 
#where 6 is start of sequence an 25 is the last element and 4 is the interval.
np.arange(6,25,4)

array([ 6, 10, 14, 18, 22])

In [239]:
#It is generally not possible to predict the number of elements obtained, due to the finite floating point precision. 
#For this reason, it is usually better to use the function "linspace" that receives as an 
#argument the number of elements that we want, instead of the step:

np.linspace(6,25,5)

array([ 6.  , 10.75, 15.5 , 20.25, 25.  ])

# Arithmetic Operations

In [240]:
#Let us do some basic arithmetic operations.
x= np.array([10,20,30,40])
y= np.array ([1,2,3,4])

add=x+y       #addition
print("Addition of x and y \n",add)

sub=x-y
print("\nSubstraction of x and y\n",sub)    #substraction

mul=x*y
print("\nMultiplication of x and y\n",mul)    #multiplication

exp= x**3     #exponent-cube of array x.
print("\nCube of x\n",exp)

div= x/y      #division
print("\nDivision of x and y\n",div)

Bool= x<10
print("\nBoolean value\n",Bool)   #boolean 


Addition of x and y 
 [11 22 33 44]

Substraction of x and y
 [ 9 18 27 36]

Multiplication of x and y
 [ 10  40  90 160]

Cube of x
 [ 1000  8000 27000 64000]

Division of x and y
 [10. 10. 10. 10.]

Boolean value
 [False False False False]


In [241]:
#Let us use some functions like sum(),min(),max().

z= np.random.random((2,3))  #Gives us a random array of 2 rows and 3 columns.
print(z)
print("\nSum of all elements \n",  z.sum())                     #Gives the sum of all the elements in the array.
print("\nMinimum vaulue of the array \n", z.min())  #Gives the minimum value in the array.
print("\nMaximum value of the array \n", z.max())               #Gives the maximum value in the array.  
print("\nSum of each column \n", z.sum(axis=0))               #This will give the sum of each column.

[[0.51406648 0.89289054 0.37143438]
 [0.13999348 0.91484914 0.47960537]]

Sum of all elements 
 3.3128393887943934

Minimum vaulue of the array 
 0.13999347651237137

Maximum value of the array 
 0.914849135561248

Sum of each column 
 [0.65405996 1.80773968 0.85103975]


In [242]:
#Let us find element-wise product and matrix-product using "*" and "@" 
A = np.array( [[9,1], [3,1]] )
B = np.array( [[4,5],[7,6]] )
print("Element-wise product\n",A * B)                  #Gives you   
print("\nMatrix-product\n",A@B)

Element-wise product
 [[36  5]
 [21  6]]

Matrix-product
 [[43 51]
 [19 21]]


In [243]:
#Universal Functions
#NumPy provides familiar mathematical functions such as sin, cos, and exp. 
#In NumPy, these are called “universal functions”(ufunc). 

B = np.arange(5)
print("B =", B)

print("\n Sin of all elements\n", np.sin(B))
print("\n Cos of all elements\n", np.cos(B))
print("\n Tan of all elements\n", np.tan(B))
print("\n Exponent of all elements\n",np.exp(B))
print("\n Square-root of all elements \n",np.sqrt(B))




B = [0 1 2 3 4]

 Sin of all elements
 [ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]

 Cos of all elements
 [ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362]

 Tan of all elements
 [ 0.          1.55740772 -2.18503986 -0.14254654  1.15782128]

 Exponent of all elements
 [ 1.          2.71828183  7.3890561  20.08553692 54.59815003]

 Square-root of all elements 
 [0.         1.         1.41421356 1.73205081 2.        ]


# Indexing, Slicing and Iterating

# One-dimensional arrays can be indexed, sliced and iterated over, as we did in lists.


In [244]:
B = np.arange(5)
print(B)
print("\n Access the element on index 1")
print(B[1])
print("\nWe can access elements from index 1 to 2")
print(B[1:3])
print("\nWe can reverse the elements in the array\n")
print(B[::-1])
print("\n We can use for loop to find the sqaure ")
for i in B:
 print (i**2)

[0 1 2 3 4]

 Access the element on index 1
1

We can access elements from index 1 to 2
[1 2]

We can reverse the elements in the array

[4 3 2 1 0]

 We can use for loop to find the sqaure 
0
1
4
9
16


# Shape Manipulation

# Changing the shape of an array

In [348]:
#Let us find the shape of the array i.e. the number of rows and columns in the matrix.

q= np.array([[2,5,6,1],[10,50,60,90],[12,22,33,44]])
print(q)
q.shape

[[ 2  5  6  1]
 [10 50 60 90]
 [12 22 33 44]]


(3, 4)

In [246]:
#Let us convert the array in a flattened form using "nparray.ravel()"

q.ravel()

array([ 2,  5,  6,  1, 10, 50, 60, 90, 12, 22, 33, 44])

In [247]:
#Let us reshape the array using "nparray.reshape()" 

q.reshape(6,2)

array([[ 2,  5],
       [ 6,  1],
       [10, 50],
       [60, 90],
       [12, 22],
       [33, 44]])

In [248]:
#Let us find the transpose of the array "using nparray.T"

q.T

array([[ 2, 10, 12],
       [ 5, 50, 22],
       [ 6, 60, 33],
       [ 1, 90, 44]])

# Stacking different arrays together

In [249]:
#Let us stack two arrays horizontally and vertically.

q= np.array([[2,5,6,1],[10,50,60,90],[12,22,33,44]])
r= np.array([[3,4,5,6],[12,13,14,15],[66,77,88,99]])
print("\nVertical Stack")
np.vstack((q,r))                               #For vertical stack use nparray.vstack()


Vertical Stack


array([[ 2,  5,  6,  1],
       [10, 50, 60, 90],
       [12, 22, 33, 44],
       [ 3,  4,  5,  6],
       [12, 13, 14, 15],
       [66, 77, 88, 99]])

In [250]:
print("\nHorizontal Stack")
np.hstack((q,r))                            #For horizontal stack use nparray.hstack()


Horizontal Stack


array([[ 2,  5,  6,  1,  3,  4,  5,  6],
       [10, 50, 60, 90, 12, 13, 14, 15],
       [12, 22, 33, 44, 66, 77, 88, 99]])

# Spliting of arrays


In [349]:
#Let us split arrays horizontally and vertically.

a = np.floor(10*np.random.random((2,10)))
a
print("\nHorizontal Split\n")
np.hsplit(a,5)    #This will split the array horizontally


Horizontal Split



[array([[0., 4.],
        [0., 5.]]), array([[6., 4.],
        [5., 3.]]), array([[2., 1.],
        [2., 9.]]), array([[1., 9.],
        [3., 3.]]), array([[4., 9.],
        [5., 0.]])]

In [252]:
print("\n Vertical Split \n")
np.vsplit(a,2)    #This will split the array vertically


 Vertical Split 



[array([[6., 4., 2., 3., 1., 3., 4., 5., 8., 3.]]),
 array([[4., 7., 0., 3., 4., 1., 1., 0., 0., 7.]])]

# Copies and Views

In [256]:
#Let us copy elements from one array to another.

a = np.floor(10*np.random.random((2,10)))
print("a=",a)
m=a            #Here we copy array a to m
m is a         #Here we check if we have properly copied the array into m or not

a= [[8. 9. 1. 1. 9. 5. 8. 6. 1. 5.]
 [2. 8. 4. 7. 8. 0. 8. 1. 1. 0.]]


True

In [257]:
#View-Different array objects can share the same data. The view method creates a new array object that looks at the same data.

n=a.view()  #Copies the structure of array but not the elements inside it
n is a

False

In [258]:
n.base is a    #Copies both elements and structure both so answer is true.

True

In [259]:
#Deep Copy-The copy method makes a complete copy of the array and its data.

d = a.copy()   # A new array object with new data is created
d is a

False

In [260]:
d.base is a  # d will not share anything with a

False









# SciPy

SciPy is a collection of mathematical algorithms and convenience functions built on the Numpy extension of Python. It adds significant power to the interactive Python session by providing the user with high-level commands and classes for manipulating and visualizing data. With SciPy an interactive Python session becomes a data-processing and system-prototyping environment rivaling systems such as MATLAB, IDL, Octave, R-Lab, and SciLab.

In [261]:
#Let us first import the package scipy beofre we use it also scipy is build on numpy so we import numpoy also.
import scipy as sp
import numpy as np

# Working with Polynomials

In SciPy, there are two ways in which we can deal with 1D polynomials. First one is using the class poly1d. This class takes coefficients or roots for initialization and forms a polynomial object. When we print this object we’ll see it prints like a polynomial.

In [266]:
from numpy import poly1d
Poly = poly1d([2,5,6])   #using the poly1d we can get the desired polynomial.
print("Polynomial is\n",Poly)

Polynomial is
    2
2 x + 5 x + 6


In [275]:
print("\nCubing the polynomial: \n")
print(Poly*Poly*Poly)      #Cubing the polynomial   


Cubing the polynomial: 

   6      5       4       3       2
8 x + 60 x + 222 x + 485 x + 666 x + 540 x + 216


In [276]:
print("\nIntegrating the polynomial: \n")
print(Poly.integ(k=4))     #we use poly.integ() to integrate the polynomial


Integrating the polynomial: 

        3       2
0.6667 x + 2.5 x + 6 x + 4


In [277]:
print("\nFinding derivative of the polynomial:")
print(Poly.deriv())      #we use poly.deriv() to derive the polynomial.


Finding derivative of the polynomial:
 
4 x + 5


In [278]:
print("\nSolving the polynomial for 2: \n")
print(Poly(9))        #we can solve the polynomial by passing the value.  


Solving the polynomial for 2: 

213


# Working with Linear Algebra

SciPy holds very fast linear algebra capabilities as it’s built using ATLAS LAPACK and BLAS libraries. The libraries are even available to use if you want more speed but you have to dig deep in that case.
All the linear algebra routines in SciPy take an object that can be converted into a 2D array and the output is of the same type.

In [285]:
#To solve linear algebra we have to import linglg command.
import numpy as np
from scipy import linalg

# Let us create an input array
A= np.array([[10,5],[20,8]])

# Let us create a solution Array
B= np.array([[8],[3]])

# Solve the linear algebra using lingalg.solve().
X= linalg.solve(A,B)

# Print results
print(X)

# To check the result we will see if all the vectors are zero or not.
print("\n Checking results, following vector should be all zeros")
print(A.dot(X)-B)

[[-2.45]
 [ 6.5 ]]

 Checking results, following vector should be all zeros
[[0.]
 [0.]]


In [321]:
#Let us find the inverse of the matrix.
A = np.array([[5,10,15],[2,4,16],[2,3,8]])
print("A=",A)

print("Inverse of matrix=",linalg.inv(A))    #We can get the inverse using "lingalg.inv()"

A= [[ 5 10 15]
 [ 2  4 16]
 [ 2  3  8]]
Inverse of matrix= [[-3.20000000e-01 -7.00000000e-01  2.00000000e+00]
 [ 3.20000000e-01  2.00000000e-01 -1.00000000e+00]
 [-4.00000000e-02  1.00000000e-01 -2.22044605e-17]]


In [320]:
#Let us find determinant of  a matrix.
import numpy as np
from scipy import linalg
A = np.array([[7,8],[9,0]])   
print("A=",A)


print("Determinant=",linalg.det(A))     #we can get the determinant using "linalg.det()"

A= [[7 8]
 [9 0]]
Determinant= -72.0


In [329]:
#Let us find the norm of matirx.
A=np.array([[7,8],[9,0]])
print("A =",A)

print("Norm =",linalg.norm(A))     #we can get the norm using "lingla.norm()"

A = [[7 8]
 [9 0]]
Norm = 13.92838827718412


In [299]:
# Let us use the vectorize function to do some basic operations
def addsubtract(a,b):
    if a > b:
        return a * b
    else:
       return a / b
vec_addsubtract = np.vectorize(addsubtract)  
vec_addsubtract([2,4,6,8],[1,3,5,7])

array([ 2, 12, 30, 56])

# SciPy Integration


In [336]:
# #To solve Integration we have to import integrate from scipy.
from scipy import integrate

# Using quad as we can see in list quad is used for simple integration
# arg1: A lambda function which returns x cubed for every x
# We'll be integrating this function
# arg2: lower limit
# arg3: upper limit
inte= integrate.quad(lambda x: x**3, 1,3)
print("Integration=",inte)

Integration= (20.0, 2.220446049250313e-13)


# SciPy Fourier Transforms
Fourier analysis helps us to express a function as a sum of periodic components and for recovering the signal from those components.

In [304]:
#To solve fourier transformation problems we have to import fft from scipy.fftpack.
from scipy.fftpack import fft
import numpy as np

x = np.array([5.0, 6.0, 7.0, -8.0, 9.5])
y = fft(x)                    #It will give us the fourier transformation.
y  

array([19.5        +0.j        , 10.59878041 -5.48808098j,
       -7.84878041+16.32309613j, -7.84878041-16.32309613j,
       10.59878041 +5.48808098j])

In [335]:
#To find the real sequence of fourier we have to import "rfft"

from scipy.fftpack import rfft
r = rfft(x)                 #It will give us the real sequence of fourier transformation.
r

array([19.5       , 10.59878041, -5.48808098, -7.84878041, 16.32309613])

In [330]:
#To find the inverse of fourier we have to import "ifft"

from scipy.fftpack import ifft
import numpy as np

yinv = ifft(y)                   #It will give us the inverse of fourier transformation.
yinv 

array([ 5. +0.j,  6. +0.j,  7. +0.j, -8. +0.j,  9.5+0.j])

# Signal Processing 

The signal processing toolbox currently contains some filtering functions, a limited set of filter design tools, and a few B-spline interpolation algorithms for one- and two-dimensional data.

In [343]:
#To find the convolution we have to import and use scipy.signal.

from scipy import signal
x = np.array([7, 8, 9])
h = np.array([4, 5, 7, 8, 0])

print("Convolution =",signal.convolve(x, h))          #we can find the convolution using singal.convolve()

Convolution = [ 28  67 125 157 127  72   0]


In [347]:
#To find the correlation we have to import and use scipy.signal.

from scipy import signal
x = np.array([7, 8, 9])
h = np.array([4, 5, 7, 8, 0])

print("Correlation =",signal.correlate(x, h))    #we can find the convolution using singal.correlate()

Correlation = [  0  56 113 163 131  77  36]


# References 

https://docs.scipy.org/doc/scipy/reference/tutorial/index.html

https://www.journaldev.com/18106/python-scipy-tutorial#importing-scipy-library